# Generated by Django 5.1.1 on 2025-04-07 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookieapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cookieconsentlog",
            name="consent_id",
            field=models.CharField(
                default="0",
                help_text="Unique identifier for consent (e.g., UUID stored in a cookie).",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cookieconsentlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Logged-in user, if available.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
