ROI = "ROI"
ROE = "ROE"
ROA = "ROA"
BVPS = "BVPS"
EPS = "EPS"
FCF = "FCF"
CUR_RATIO = "cur_ratio"
DEBT_TO_EQUITY = "debt_to_equity"
PAYOUT = "payout"


ID = "id"
YEAR = "year"
REVENUE = "revenue"
NET_INCOME = "net_income"
CASH = "cash"
CUR_ASSETS = "cur_assets"
NCUR_ASSETS = "ncur_assets"
TOTAL_ASSETS = "total_assets"
EQUITY = "equity"
CUR_LIABILITIES = "cur_liabilities"
NCUR_LIABILITIES = "ncur_liabilities"
TOTAL_LIABILITIES = "total_liabilities"
DIVIDENDS = "dividends"
BUYBACKS = "buybacks"
SHARES = "shares"
PRICE = "price"